package arm9_timing_pkg;
  typedef enum logic [2:0] {
    ARM9_BUS_CYCLE_UNSPECIFIED,
    ARM9_BUS_CYCLE_INTERNAL,
    ARM9_BUS_CYCLE_NONSEQUENTIAL,
    ARM9_BUS_CYCLE_SEQUENTIAL,
    ARM9_BUS_CYCLE_COPROCESSOR
  } arm9_bus_cycle_e;

  typedef enum logic [1:0] {
    ARM9_LOAD_TIMING_NORMAL,
    ARM9_LOAD_TIMING_WORD_INTERLOCK,
    ARM9_LOAD_TIMING_ROTATE_INTERLOCK,
    ARM9_LOAD_TIMING_PC_DESTINATION
  } arm9_load_timing_class_e;
endpackage
